"""modified tables

Revision ID: 13350a545abe
Revises: 92b579155f59
Create Date: 2024-04-08 16:21:43.030088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13350a545abe'
down_revision = '92b579155f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(), nullable=True))

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
